# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:14.18.0

pipelines:
  branches:
    develop:
      - step:
          name: Sonar
          script:
            - npm ci
            - npm run sonar
    master:
      - step:
          size: 2x # Double resources available for this step.
          name: Deploy to production
          deployment: production
          script: # Modify the commands below to build your repository.
            - npm install
            - npm run build:prod
            - pipe: atlassian/aws-s3-deploy:0.3.8
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: "eu-west-1"
                S3_BUCKET: "drwolf-impaqts-frontend"
                LOCAL_PATH: "dist/impaqts-fe"
                ACL: "public-read"
            - pipe: atlassian/aws-cloudfront-invalidate:0.6.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID # Optional if already defined in the context or OIDC used.
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY # Optional if already defined in the context or OIDC used.
                AWS_DEFAULT_REGION: "eu-west-1" # Optional if already defined in the context.
                DISTRIBUTION_ID: "E263CTGMHO0P4P"
