/** PAGE */
export const WORD_LIST_OPTION_LABEL = 'OPTION_LABEL.WORD_LIST';
export const SORT_OPTION_LABEL = 'OPTION_LABEL.SORT';
export const FREQ_OPTION_LABEL = 'OPTION_LABEL.FREQUENCY';
export const VIEW_OPTION_LABEL = 'OPTION_LABEL.VIEW';
export const COLLOCATION_OPTION_LABEL = 'OPTION_LABEL.COLLOCATION';
export const FILTER_OPTION_LABEL = 'OPTION_LABEL.FILTER';
export const CREDITS = 'CREDITS';
export const COPYRIGHT = 'COPYRIGHT';
export const CONCORDANCE_SIMPLE = 'PAGE.CONCORDANCE.SIMPLE';
export const CONCORDANCE_LEMMA = 'PAGE.CONCORDANCE.LEMMA';
export const CONCORDANCE_PHRASE = 'PAGE.CONCORDANCE.PHRASE';
export const CONCORDANCE_WORD = 'PAGE.CONCORDANCE.WORD';
export const CONCORDANCE_CHARACTER = 'PAGE.CONCORDANCE.CHARACTER';
export const CONCORDANCE_CQL = 'PAGE.CONCORDANCE.CQL';
export const SELECT_CORPUS_LABEL = 'PAGE.CONCORDANCE.SELECT_CORPUS';

/** MENU LABELS */
export const MENU_LOGIN = 'MENU.LOGIN';
export const MENU_CONCORDANCE = 'MENU.CONCORDANCE';
export const MENU_WORD_LIST = 'MENU.WORD_LIST';
export const MENU_CORPUS_INFO = 'MENU.CORPUS_INFO';
export const MENU_ALL_WORDS = 'MENU.ALL_WORDS';
export const MENU_ALL_LEMMAS = 'MENU.ALL_LEMMAS';
export const MENU_VIEW_OPTION = 'MENU.VIEW_OPTION';
export const MENU_SORT = 'MENU.SORT';
export const MENU_FILTER = 'MENU.FILTER';
export const MENU_FREQUENCY = 'MENU.FREQUENCY';
export const MENU_COLLOCATION = 'MENU.COLLOCATION';
export const MENU_VISUAL_QUERY = 'MENU.VISUAL_QUERY';
export const MENU_CREDITS = 'MENU.CREDITS';
export const MENU_COPYRIGHT = 'MENU.COPYRIGHT';
export const MENU_POC = 'MENU.POC';
export const MENU_RESULT_CONCORDANCE = 'MENU.RESULT_CONCORDANCE';
export const MENU_AS_SUBCORPUS = 'MENU.AS_SUBCORPUS'
