export const CONCORDANCE = 'concordance';
export const SIMPLE = 'simple';
export const LEMMA = 'lemma';
export const PHRASE = 'phrase';
export const WORD = 'word';
export const CHARACTER = 'character';
export const CQL = 'cql';

export enum REQUEST_TYPE {
  VISUAL_QUERY_REQUEST = 'VISUAL_QUERY_REQUEST',
  TEXTUAL_QUERY_REQUEST = 'TEXTUAL_QUERY_REQUEST',
  CONTEXT_QUERY_REQUEST = 'CONTEXT_QUERY_REQUEST',
  COLLOCATION_REQUEST = 'COLLOCATION_REQUEST',
  QUICK_SORT_REQUEST = 'QUICK_SORT_REQUEST',
  MULTI_FREQUENCY_QUERY_REQUEST = 'MULTI_FREQUENCY_QUERY_REQUEST',
  CONC_FREQUENCY_QUERY_REQUEST = 'CONC_FREQUENCY_QUERY_REQUEST',
  POSITIVE_FREQUEQUENCY_CONCORDANCE_QUERY_REQUEST = 'POSITIVE_FREQUEQUENCY_CONCORDANCE_QUERY_REQUEST',
  WIDE_CONTEXT_QUERY_REQUEST = 'WIDE_CONTEXT_QUERY_REQUEST',
}
