/** SORT & FREQ */
export const FIRST = 'first';
export const SECOND = 'second';
export const THIRD = 'third';
export const FOURTH = 'fourth';
export const L6 = '6L';
export const L5 = '5L';
export const L4 = '4L';
export const L3 = '3L';
export const L2 = '2L';
export const L1 = '1L';
export const R6 = '6R';
export const R5 = '5R';
export const R4 = '4R';
export const R3 = '3R';
export const R2 = '2R';
export const R1 = '1R';

export const WORD = 'word';
export const LEFT = 'left';
export const RIGHT = 'right';
export const NODE = 'node';
export const MULTILEVEL = 'multilevel';
